blank_issues_enabled: false
contact_links:
  - name: Current Version
    url: https://ayushagnihotri2025.github.io/YouTube-Ads-Clone/
    about: You can check our it's current version of the code here.